version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: meditate-server
    container_name: meditate-node-server
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: meditate-client
    container_name: meditate-react-client
    volumes:
      - ./client/:/app
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
